name=UniversalRemoteDecoder
version=1.0.0
author=mendi
maintainer=Carlos Garcia Mendizabal <soycarlosmendi@gmail.com>
sentence=Non-blocking decoder library to manage IR remote controls with multiple profiles.
paragraph=Object-oriented, non-blocking library wich allows dynamic mapping of hexadecimal IR codes to standard ENUMS, making it ideal for state machines.
category=Device Control
url=https://github.com/lumelee/UniversalRemote.git
architectures=*
depends=IRremote
